config/routes.rb
Rails.application.routes.draw do
  resources :guests
  resources :control_panels
  resources :blogs
  root to: 'users#index'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/control_panel.rb
class ControlPanel < ApplicationRecord
end

app/controllers/control_panels_controller.rb
class ControlPanelsController < ApplicationController
  before_action :set_control_panel, only: [:show, :edit, :update, :destroy]

  # GET /control_panels
  # GET /control_panels.json
  def index
    @control_panels = ControlPanel.all
  end

  # GET /control_panels/1
  # GET /control_panels/1.json
  def show
  end

  # GET /control_panels/new
  def new
    @control_panel = ControlPanel.new
  end

  # GET /control_panels/1/edit
  def edit
  end

  # POST /control_panels
  # POST /control_panels.json
  def create
    @control_panel = ControlPanel.new(control_panel_params)

    respond_to do |format|
      if @control_panel.save
        format.html { redirect_to @control_panel, notice: 'Control panel was successfully created.' }
        format.json { render :show, status: :created, location: @control_panel }
      else
        format.html { render :new }
        format.json { render json: @control_panel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /control_panels/1
  # PATCH/PUT /control_panels/1.json
  def update
    respond_to do |format|
      if @control_panel.update(control_panel_params)
        format.html { redirect_to @control_panel, notice: 'Control panel was successfully updated.' }
        format.json { render :show, status: :ok, location: @control_panel }
      else
        format.html { render :edit }
        format.json { render json: @control_panel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /control_panels/1
  # DELETE /control_panels/1.json
  def destroy
    @control_panel.destroy
    respond_to do |format|
      format.html { redirect_to control_panels_url, notice: 'Control panel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_control_panel
      @control_panel = ControlPanel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def control_panel_params
      params.fetch(:control_panel, {})
    end
end

app/helpers/control_panels_helper.rb
module ControlPanelsHelper
end

app/views/control_panels/_form.html.erb
<%= form_for(control_panel) do |f| %>
  <% if control_panel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(control_panel.errors.count, "error") %> prohibited this control_panel from being saved:</h2>

      <ul>
      <% control_panel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/control_panels/edit.html.erb
<h1>Editing Control Panel</h1>

<%= render 'form', control_panel: @control_panel %>

<%= link_to 'Show', @control_panel %> |
<%= link_to 'Back', control_panels_path %>

app/views/control_panels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Control Panels</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @control_panels.each do |control_panel| %>
      <tr>
        <td><%= link_to 'Show', control_panel %></td>
        <td><%= link_to 'Edit', edit_control_panel_path(control_panel) %></td>
        <td><%= link_to 'Destroy', control_panel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Control Panel', new_control_panel_path %>

app/views/control_panels/new.html.erb
<h1>New Control Panel</h1>

<%= render 'form', control_panel: @control_panel %>

<%= link_to 'Back', control_panels_path %>

app/views/control_panels/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_control_panel_path(@control_panel) %> |
<%= link_to 'Back', control_panels_path %>